# Docker Compose for LangOps Documentation
version: '3.8'

services:
  langops-docs:
    build:
      context: .
      dockerfile: Dockerfile.langops.docs
    container_name: langops-docs
    ports:
      - "8000:8000"
    volumes:
      # Mount source directories for live reload during development
      - ./docs:/app/docs:ro
      - ./mkdocs.yml:/app/mkdocs.yml:ro
      - ./README.md:/app/README.md:ro
      - ./LICENSE:/app/LICENSE:ro
      - ./CODE_OF_CONDUCT.md:/app/CODE_OF_CONDUCT.md:ro
      - ./CHANGELOG.md:/app/CHANGELOG.md:ro
    environment:
      - PYTHONPATH=/app
      - MKDOCS_CONFIG_FILE=mkdocs.yml
    restart: unless-stopped
    networks:
      - langops-docs-network

networks:
  langops-docs-network:
    driver: bridge

# Optional: Add a reverse proxy for production
# nginx:
#   image: nginx:alpine
#   ports:
#     - "80:80"
#     - "443:443"
#   volumes:
#     - ./nginx.conf:/etc/nginx/nginx.conf:ro
#   depends_on:
#     - langops-docs
#   networks:
#     - langops-docs-network
